# Site settings
# These are used to personalize your new site.
title: Jacob Alexander Braddock # your name here
logo: "/images/braddock.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Cybersecurity (class of 2025)
  <br /><br />
  <a href="https://csustudentnet-my.sharepoint.com/:w:/g/personal/jabraddock_csustudent_net/ES8gF_gsUd9NmDyr43r4RaMB3E_ZVWH2vaYyOCc4dF6gcg?e=L4PoXh">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/jacob-braddock-10155b2ab/">View My LinkedIn Profile</a>
repository: "csci-csu/csci-portfolio"
github_username:  PJB02 # update with your username

# Build setting
theme: jekyll-theme-minimal

